name: redstone_mapper_mongo
version: 0.1.2
author: Luiz Mineo <luiz.mineo@gmail.com>
description: MongoDB extension for redstone_mapper 
homepage: http://redstonedart.org
environment:
  sdk: '>=1.4.0 <2.0.0'
dependencies:
  redstone: '>= 0.5.5 < 0.6.0'
  redstone_mapper: '>= 0.1.1 <0.2.0'
  connection_pool: '>=0.1.0+2 < 1.0.0'
  mongo_dart: '>= 0.1.40 <0.2.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
  mock: '>=0.11.0+1 <0.12.0'
